/*******************************************************************
* Client: PHARMA Private Limited.
* Project: Protocol: 043-1-2025
* Program: T_14_1_1.SAS
*
* Program Type: Table
*
* Purpose: To produce Table 14.1.1 Subject Disposition by Treatment
*          (Safety Population)
* Usage Notes: Uses the ADSL safety population to summarize subject
*              disposition by treatment; creates OUTPUTS/T_14_1_1.RTF.
*
* SAS® Version: Base SAS 9.4_M8
* Operating System: SAS OnDemand Linux server (client: Windows 11)
*
* Author: ANSANIA SALAM
* Date Created: 20MAY2026
* Modification History: 06OCT2026
*******************************************************************/

LIBNAME ADAM "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/ADaM";

/*header cap N /big N counts- always take from adsl*/
DATA ADSL1;
SET ADAM.ADSL;
IF SAFFL='Y';
OUTPUT;
TRT01AN=5;
TRT01A='ALL';
OUTPUT;
KEEP USUBJID TRT01AN TRT01A;
RUN;

PROC SQL NOPRINT;
CREATE TABLE TRT AS
SELECT TRT01AN, TRT01A, COUNT(DISTINCT USUBJID) AS DENOM
FROM ADSL1
GROUP BY TRT01AN, TRT01A
ORDER BY TRT01AN, TRT01A;

SELECT DENOM INTO :BIGN1-:BIGN5
FROM TRT
ORDER BY TRT01AN;
QUIT;

%PUT &BIGN1 &BIGN2 &BIGN3 &BIGN4 &BIGN5;

/*BODY PART*/
DATA ADSL2;
SET ADAM.ADSL;
IF SAFFL='Y';
OUTPUT;
TRT01AN=5;
TRT01A='ALL';
OUTPUT;
KEEP USUBJID TRT01AN TRT01A TRT01P ENRLFL EOSSTT DCSREAS;
RUN;

/*Subjects Planned treatment*/
PROC SQL NOPRINT;
CREATE TABLE SPT AS
SELECT TRT01AN, TRT01A, "Subjects Planned treatment" AS POP LENGTH=100,
1 AS ORD, COUNT(DISTINCT USUBJID) AS N
FROM ADSL2
WHERE NOT MISSING(TRT01P)
GROUP BY TRT01AN, TRT01A;
QUIT;

/*Subjects Enrolled*/
PROC SQL NOPRINT;
CREATE TABLE SE AS
SELECT TRT01AN, TRT01A, "Subjects Enrolled" AS POP LENGTH=100,
2 AS ORD, COUNT(DISTINCT USUBJID) AS N
FROM ADSL2
WHERE ENRLFL='Y'
GROUP BY TRT01AN, TRT01A;
QUIT;

/*Subjects Withdrawn*/
PROC SQL NOPRINT;
CREATE TABLE SW AS
SELECT TRT01AN, TRT01A, "Subjects Withdrawn" AS POP LENGTH=100,
3 AS ORD, COUNT(DISTINCT USUBJID) AS N
FROM ADSL2
WHERE EOSSTT='DISCONTINUED'
GROUP BY TRT01AN, TRT01A;
QUIT;

/*REASONS*/
PROC SQL NOPRINT;
CREATE TABLE SWR AS
SELECT TRT01AN, TRT01A, DCSREAS AS POP LENGTH=100,
4 AS ORD, COUNT(DISTINCT USUBJID) AS N
FROM ADSL2
WHERE EOSSTT='DISCONTINUED' AND NOT MISSING(DCSREAS)
GROUP BY TRT01AN, TRT01A, DCSREAS;
QUIT;

DATA SWR;
SET SWR;
POP="   "||STRIP(POP);
RUN;

DATA FINAL_CT;
SET SPT SE SW SWR;
RUN;

PROC SQL;
CREATE TABLE ROWS AS
SELECT DISTINCT ORD, POP
FROM FINAL_CT;

CREATE TABLE SKELETON AS
SELECT G.TRT01AN, G.TRT01A, G.DENOM, R.ORD, R.POP
FROM TRT AS G, ROWS AS R;

CREATE TABLE CELLS AS
SELECT S.TRT01AN, S.TRT01A, S.DENOM, S.ORD, S.POP,
COALESCE(C.N, 0) AS N
FROM SKELETON AS S
LEFT JOIN FINAL_CT AS C
ON S.TRT01AN=C.TRT01AN
AND S.ORD=C.ORD
AND S.POP=C.POP
ORDER BY S.ORD, S.POP, S.TRT01AN;
QUIT;

/*PCT*/
DATA PCT;
SET CELLS;
LENGTH DISPLAY $30;
PCT1=N/DENOM*100;
DISPLAY=CAT(STRIP(PUT(N,4.))," (",STRIP(PUT(PCT1,5.1)),")");
RUN;

PROC SORT DATA=PCT;
BY ORD POP TRT01AN;
RUN;

PROC TRANSPOSE DATA=PCT OUT=FINAL(DROP=_NAME_) PREFIX=TRT;
BY ORD POP;
ID TRT01AN;
VAR DISPLAY;
RUN;

%INCLUDE "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/Macro/RTF.sas";

OPTIONS ORIENTATION=LANDSCAPE;
ODS ESCAPECHAR='^';
ODS SELECT ALL;

TITLE1 J=L "PHARMA Private Limited.";
TITLE2 J=L "Protocol: 043-1-2025";
TITLE3 J=C "Table 14.1.1 Subject Disposition by Treatment (Safety Population)";

FOOTNOTE1 J=L "Ansania_MCC_Immunotherapy_Phase1/MCCTables/T_14_1_1.sas";

ODS RTF FILE="/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/OUTPUTS/T_14_1_1.RTF"
STYLE=Styles.Test;

PROC REPORT DATA=FINAL NOWD STYLE={OUTPUTWIDTH=100%} MISSING SPLIT='|';
COLUMN ORD POP TRT1 TRT2 TRT3 TRT4 TRT5;

DEFINE ORD / ORDER NOPRINT;

DEFINE POP / "Population"
STYLE(COLUMN)={JUST=L CELLWIDTH=39% ASIS=ON}
STYLE(HEADER)={JUST=L CELLWIDTH=39% ASIS=ON};

DEFINE TRT1 / "DRUG A|(N=&BIGN1)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE TRT2 / "DRUG B|(N=&BIGN2)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE TRT3 / "DRUG C|(N=&BIGN3)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE TRT4 / "DRUG D|(N=&BIGN4)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE TRT5 / "ALL|(N=&BIGN5)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

COMPUTE BEFORE _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

RUN;

ODS _ALL_ CLOSE;



