/*******************************************************************
* Client: PHARMA Private Limited.
* Project: Protocol: 043-1-2025
* Program: T_14_1_4.SAS
*
* Program Type: Table
*
* Purpose: To produce Table 14.1.4 Treatment Emergent Adverse Events
*          by Treatment, System Organ Class and Preferred Term
*          (DLT Evaluable Population)
* Usage Notes: Reports unique subjects with TEAEs by treatment,
*              system organ class and preferred term.
*
* SAS Version: Base SAS 9.4_M8
* Operating System: SAS OnDemand Linux server (client: Windows 11)
*
* Author: ANSANIA SALAM
* Date Created: 05JUN2026
* Modification History: 070CT2026
*******************************************************************/

LIBNAME ADAM "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/ADaM";

/* Header cap N / big N counts - always take from ADSL */

DATA ADSL_DLT;
SET ADAM.ADSL;
WHERE DLTEVLFL='Y';
KEEP USUBJID TRT01AN TRT01A;
RUN;

PROC SQL;
CREATE TABLE TRT_COUNT AS
SELECT TRT01AN, COUNT(DISTINCT USUBJID) AS DENOM
FROM ADSL_DLT
GROUP BY TRT01AN;
QUIT;

DATA TRT_GRID;
DO TRT01AN=1 TO 4;
OUTPUT;
END;
RUN;

PROC SQL;
CREATE TABLE TRT AS
SELECT G.TRT01AN, COALESCE(C.DENOM,0) AS DENOM
FROM TRT_GRID AS G
LEFT JOIN TRT_COUNT AS C
ON G.TRT01AN=C.TRT01AN
ORDER BY G.TRT01AN;
QUIT;

PROC SQL NOPRINT;
SELECT DENOM INTO :BIGN1-:BIGN4
FROM TRT
ORDER BY TRT01AN;
QUIT;

%PUT &BIGN1 &BIGN2 &BIGN3 &BIGN4;

/* Body part */

/* Sort ADAE and the DLT-evaluable ADSL subjects before merging */

PROC SORT DATA=ADAM.ADAE OUT=ADAE_SORT;
BY USUBJID;
RUN;

PROC SORT DATA=ADSL_DLT OUT=ADSL_DLT_SORT;
BY USUBJID;
RUN;

DATA ADAE;
MERGE ADAE_SORT(IN=A) ADSL_DLT_SORT(IN=B);
BY USUBJID;

IF A AND B;
IF TRTEMFL='Y';

AEBODSYS=UPCASE(STRIP(AEBODSYS));
IF MISSING(AEBODSYS) THEN AEBODSYS='UNCODED';

IF MISSING(AEDECOD) THEN AEDECOD='Uncoded';

KEEP USUBJID TRT01AN TRT01A AEBODSYS AEDECOD TRTEMFL;
RUN;

/* Diagnostic check: confirm eligible TEAE records were selected */

PROC FREQ DATA=ADAE;
TABLES TRT01AN AEBODSYS AEDECOD / MISSING;
RUN;

/* Number of subjects with TEAEs */

PROC SQL;
CREATE TABLE NOS_COUNT AS
SELECT TRT01AN, COUNT(DISTINCT USUBJID) AS N
FROM ADAE
GROUP BY TRT01AN;

CREATE TABLE NOS AS
SELECT T.TRT01AN,
       'Number of Subjects with TEAEs' AS AEBODSYS LENGTH=200,
       '' AS AEDECOD LENGTH=200,
       1 AS ORD,
       COALESCE(C.N,0) AS N,
       'Number of Subjects' AS IDN LENGTH=30
FROM TRT AS T
LEFT JOIN NOS_COUNT AS C
ON T.TRT01AN=C.TRT01AN;
QUIT;

/* MedDRA system organ class */

PROC SQL;
CREATE TABLE SOC AS
SELECT TRT01AN,
       AEBODSYS,
       '' AS AEDECOD LENGTH=200,
       2 AS ORD,
       COUNT(DISTINCT USUBJID) AS N,
       'SYSTEM ORGAN CLASS' AS IDN LENGTH=30
FROM ADAE
GROUP BY TRT01AN, AEBODSYS;
QUIT;

/* MedDRA preferred term */

PROC SQL;
CREATE TABLE PT AS
SELECT TRT01AN,
       AEBODSYS,
       AEDECOD,
       3 AS ORD,
       COUNT(DISTINCT USUBJID) AS N,
       'Preferred Term' AS IDN LENGTH=30
FROM ADAE
GROUP BY TRT01AN, AEBODSYS, AEDECOD;
QUIT;

DATA FINAL_CT;
SET NOS SOC PT;
RUN;

PROC SORT DATA=FINAL_CT;
BY TRT01AN;
RUN;

PROC SORT DATA=TRT;
BY TRT01AN;
RUN;

/* Percentages */

DATA PCT;
MERGE FINAL_CT(IN=A) TRT(IN=B);
BY TRT01AN;

IF A;

IF DENOM>0 THEN PCT1=N/DENOM*100;
ELSE PCT1=0;

LENGTH PCT_VALUE $30;
PCT_VALUE=STRIP(PUT(N,4.))||' ('||
          STRIP(PUT(PCT1,5.1))||')';
RUN;

PROC SORT DATA=PCT;
BY ORD AEBODSYS AEDECOD IDN;
RUN;

/* Transpose treatment groups into report columns TRT1-TRT4 */

PROC TRANSPOSE DATA=PCT OUT=PCT_T PREFIX=TRT;
BY ORD AEBODSYS AEDECOD IDN;
ID TRT01AN;
VAR PCT_VALUE;
RUN;

/* Fill treatment-group combinations with zero where no event occurred */

DATA FINAL;
SET PCT_T;
LENGTH NEW $200 TRT1-TRT4 $30;

IF MISSING(TRT1) THEN TRT1='0 (0.0)';
IF MISSING(TRT2) THEN TRT2='0 (0.0)';
IF MISSING(TRT3) THEN TRT3='0 (0.0)';
IF MISSING(TRT4) THEN TRT4='0 (0.0)';

IF IDN='Preferred Term' THEN NEW='   '||STRIP(AEDECOD);
ELSE NEW=STRIP(AEBODSYS);
RUN;

/* Add page breaks */

PROC SORT DATA=FINAL;
BY ORD AEBODSYS AEDECOD IDN;
RUN;

DATA FINAL;
SET FINAL;
RETAIN LNT PAG1 0;
LNT+1;

IF LNT>22 THEN DO;
PAG1=PAG1+1;
LNT=1;
END;
RUN;

/* Report */

%INCLUDE "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/Macro/RTF.sas";

OPTIONS ORIENTATION=LANDSCAPE;

TITLE1 J=L "PHARMA Private Limited.";
TITLE2 J=L "Protocol: 043-1-2025";
TITLE3 J=C "Table 14.1.4 Treatment Emergent Adverse Events by Treatment, System Organ Class and Preferred Term (DLT Evaluable Population)";
TITLE4 J=C "TRTEMFL='Y' AND DLTEVLFL='Y'";

FOOTNOTE1 J=L
"Ansania_MCC_Immunotherapy_Phase1/MCCTables/T_14_1_4.sas";

ODS ESCAPECHAR='^';

ODS RTF FILE=
"/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/OUTPUTS/T_14_1_4.RTF"
STYLE=Styles.Test;

PROC REPORT DATA=FINAL NOWD STYLE={OUTPUTWIDTH=100%} MISSING SPLIT='|';
COLUMN PAG1 ORD AEBODSYS AEDECOD NEW
       ("Treatment" TRT1 TRT2 TRT3 TRT4);

DEFINE PAG1 / ORDER NOPRINT;
DEFINE ORD / ORDER NOPRINT;
DEFINE AEBODSYS / ORDER NOPRINT;
DEFINE AEDECOD / ORDER NOPRINT;

DEFINE NEW / DISPLAY
"MedDRA System Organ Class|MedDRA Preferred Term"
STYLE(COLUMN)={JUST=L CELLWIDTH=59% ASIS=ON}
STYLE(HEADER)={JUST=L CELLWIDTH=59% ASIS=ON};

DEFINE TRT1 / DISPLAY "DRUG A|(N=&BIGN1)"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

DEFINE TRT2 / DISPLAY "DRUG B|(N=&BIGN2)"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

DEFINE TRT3 / DISPLAY "DRUG C|(N=&BIGN3)"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

DEFINE TRT4 / DISPLAY "DRUG D|(N=&BIGN4)"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

COMPUTE BEFORE _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE BEFORE AEBODSYS;
LINE '';
ENDCOMP;

BREAK AFTER PAG1 / PAGE;
RUN;

ODS _ALL_ CLOSE;










