/*******************************************************************
* Client: PHARMA Private Limited.
* Project: Protocol: 043-1-2025
* Program: L_16_2_1_4.SAS
*
* Program Type: Listing
*
* Purpose: To produce 16.2.1.4 Subject Demographics
* Usage Notes: Uses ADAM.ADSL; displays HEIGHTBL, WEIGHTBL, and BMIBL to one decimal place; 
*              creates OUTPUTS/L_16_2_1_4
*
* SAS Version: Base SAS 9.4_M8
* Operating System: SAS OnDemand Linux server (client: Windows 11)
*
* Author: ANSANIA SALAM
* Date Created: 10JUL2026
* Modification History: 05OCT2026
*******************************************************************/

LIBNAME ADAM "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/ADaM";

PROC SORT DATA=ADAM.ADSL OUT=LISTING_DEMO;
BY USUBJID;
RUN;

%INCLUDE "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/Macro/RTF.sas";

OPTIONS ORIENTATION=LANDSCAPE;
TITLE1 J=L "PHARMA Private Limited.";
TITLE2 J=L "Protocol: 043-1-2025";
TITLE3 J=C "16.2.1.4 Subject Demographics";
FOOTNOTE1 J=L "Ansania_MCC_Immunotherapy_Phase1/MCCListings/L_16_2_1_4.sas";

ODS ESCAPECHAR='^';
ODS RTF FILE= "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/OUTPUTS/L_16_2_1_4.RTF"
STYLE=Styles.Test;

PROC REPORT DATA=LISTING_DEMO NOWD STYLE={OUTPUTWIDTH=100%} MISSING SPLIT='|';
COLUMN USUBJID TRT01P AGE SEX RACE HEIGHTBL WEIGHTBL BMIBL;

DEFINE USUBJID / ORDER "Subject|Number"
STYLE(COLUMN)={JUST=L CELLWIDTH=15%}
STYLE(HEADER)={JUST=L CELLWIDTH=15%};

DEFINE TRT01P / DISPLAY "Treatment|Sequence"
STYLE(COLUMN)={JUST=L CELLWIDTH=15%}
STYLE(HEADER)={JUST=L CELLWIDTH=15%};

DEFINE AGE / DISPLAY "Age*|(years)"
STYLE(COLUMN)={JUST=L CELLWIDTH=9%}
STYLE(HEADER)={JUST=L CELLWIDTH=9%};

DEFINE SEX / DISPLAY "Sex"
STYLE(COLUMN)={JUST=L CELLWIDTH=8%}
STYLE(HEADER)={JUST=L CELLWIDTH=8%};

DEFINE RACE / DISPLAY "Race"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE HEIGHTBL / DISPLAY "Height|(cm)" FORMAT=8.1
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE WEIGHTBL / DISPLAY "Weight|(kg)" FORMAT=8.1
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE BMIBL / DISPLAY "BMI|(kg/m2)" FORMAT=8.1
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

COMPUTE BEFORE _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;
RUN;

ODS _ALL_ CLOSE;