/*******************************************************************
* Client: PHARMA Private Limited.
* Project: Protocol: 043-1-2025
* Program: L_16_2_2_4.SAS
*
* Program Type: Listing
*
* Purpose: To Produce 16.2.2.4 Adverse Events
* Usage Notes: Uses ADAM.ADAE; selects records with a nonblank AETERM; 
*               creates OUTPUTS/L_16_2_2_4.RTF.
*
* SAS Version: Base SAS 9.4_M8
* Operating System: SAS OnDemand Linux server (client: Windows 11).
*
* Author: ANSANIA SALAM
* Date Created: 10AUG2026
* Modification History: 05OCT2026
*******************************************************************/

LIBNAME ADAM "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/ADaM";

DATA LISTING_AE;
SET ADAM.ADAE;
IF AETERM NE '';
SPA = CATX("/", AETERM, AEBODSYS, AEDECOD);
KEEP USUBJID SPA AESTDTC AEENDTC AESER AEACN AEREL AEOUT;
RUN;

DATA LISTING_AE;
SET LISTING_AE;
RETAIN LNT PAG1 0;
LNT + 1;
IF LNT > 7 THEN DO;
PAG1 = PAG1 + 1;
LNT = 1;
END;
RUN;

%INCLUDE "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/Macro/RTF.sas";

OPTIONS ORIENTATION=LANDSCAPE;
TITLE1 J=L "PHARMA Private Limited.";
TITLE2 J=L "Protocol: 043-1-2025";
TITLE3 J=C "16.2.2.4 Adverse Events";
FOOTNOTE1 J=L "Ansania_MCC_Immunotherapy_Phase1/MCCListings/L_16_2_2_4.sas";

ODS ESCAPECHAR='^';
ODS RTF FILE= "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/OUTPUTS/L_16_2_2_4.RTF"
STYLE=Styles.Test;

PROC REPORT DATA=LISTING_AE NOWD STYLE={OUTPUTWIDTH=100%} MISSING SPLIT='|';
COLUMN PAG1 USUBJID SPA AESTDTC AEENDTC AESER AEACN AEREL AEOUT;

DEFINE PAG1 / ORDER NOPRINT;

DEFINE USUBJID / ORDER "Subj.|No."
STYLE(COLUMN)={JUST=L CELLWIDTH=15%}
STYLE(HEADER)={JUST=L CELLWIDTH=15%};

DEFINE SPA / ORDER
"Adverse Event/Primary System Organ|Class/Preferred Term"
STYLE(COLUMN)={JUST=L CELLWIDTH=25%}
STYLE(HEADER)={JUST=L CELLWIDTH=25%};

DEFINE AESTDTC / DISPLAY "Start|Date/Time"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

DEFINE AEENDTC / DISPLAY "End|Date/Time"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

DEFINE AESER / DISPLAY "Serious|Event"
STYLE(COLUMN)={JUST=L CELLWIDTH=6%}
STYLE(HEADER)={JUST=L CELLWIDTH=6%};

DEFINE AEACN / DISPLAY "Action Taken"
STYLE(COLUMN)={JUST=L CELLWIDTH=8%}
STYLE(HEADER)={JUST=L CELLWIDTH=8%};

DEFINE AEREL / DISPLAY "Relationship|to Study Drug"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

DEFINE AEOUT / DISPLAY "Outcome"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

COMPUTE BEFORE _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

BREAK AFTER PAG1 / PAGE;
RUN;

ODS _ALL_ CLOSE;