/*******************************************************************
* Client: PHARMA Private Limited.
* Project: Protocol: 043-1-2025
* Program: L_16_2_1_9.SAS
*
* Program Type: Listing
*
* Purpose: To produce 16.2.1.9 Urinalysis
* Usage Notes: Uses ADAM.ADLB; selects urinalysis results; creates OUTPUTS/L_16_2_1_9.RTF.
*
* SAS Version: Base SAS 9.4_M8
* Operating System: SAS OnDemand Linux server (client: Windows 11)  
*
* Author: ANSANIA SALAM
* Date Created: 25JUL2026
* Modification History: 05OCT2026
*******************************************************************/

LIBNAME ADAM "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/ADaM";

DATA LISTING_UA;
SET ADAM.ADLB;
WHERE UPCASE(STRIP(PARCAT1)) = "URINALYSIS";

ADTC = STRIP(PUT(ADT, DATE9.));

KEEP USUBJID PARAMN PARAM AVISITN AVISIT ADT ADTC AVALC;
RUN;

PROC SORT DATA=LISTING_UA;
BY USUBJID PARAMN AVISITN ADT;
RUN;

%INCLUDE "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/Macro/RTF.sas";

OPTIONS ORIENTATION=LANDSCAPE;
TITLE1 J=L "PHARMA Private Limited.";
TITLE2 J=L "Protocol: 043-1-2025";
TITLE3 J=C "16.2.1.9 Urinalysis";
FOOTNOTE1 J=L "Ansania_MCC_Immunotherapy_Phase1/MCCListings/L_16_2_1_9.sas";

ODS ESCAPECHAR='^';
ODS RTF FILE= "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/OUTPUTS/L_16_2_1_9.RTF"
STYLE=Styles.Test;

PROC REPORT DATA=LISTING_UA NOWD
STYLE={OUTPUTWIDTH=100%} MISSING SPLIT='|';

COLUMN USUBJID PARAMN PARAM AVISITN AVISIT ADT ADTC AVALC;

DEFINE USUBJID / ORDER "Subject|Number"
STYLE(COLUMN)={JUST=L CELLWIDTH=20%}
STYLE(HEADER)={JUST=L CELLWIDTH=20%};

DEFINE PARAMN / ORDER NOPRINT;

DEFINE PARAM / ORDER "Test"
STYLE(COLUMN)={JUST=L CELLWIDTH=25%}
STYLE(HEADER)={JUST=L CELLWIDTH=25%};

DEFINE AVISITN / ORDER NOPRINT;

DEFINE AVISIT / ORDER "Visit"
STYLE(COLUMN)={JUST=L CELLWIDTH=20%}
STYLE(HEADER)={JUST=L CELLWIDTH=20%};

DEFINE ADT / ORDER NOPRINT;

DEFINE ADTC / DISPLAY "Date/Time of|Measurement"
STYLE(COLUMN)={JUST=L CELLWIDTH=20%}
STYLE(HEADER)={JUST=L CELLWIDTH=20%};

DEFINE AVALC / DISPLAY "Result"
STYLE(COLUMN)={JUST=L CELLWIDTH=15%}
STYLE(HEADER)={JUST=L CELLWIDTH=15%};

COMPUTE BEFORE _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;
RUN;

ODS _ALL_ CLOSE;