/*******************************************************************
* Client: PHARMA Private Limited.
* Project: Protocol: 043-1-2025
* Program: T_14_1_5.SAS
*
* Program Type: Table
*
* Purpose: To produce Table 14.1.5 Summary of Changes in Vital Signs
*          from Baseline to Final Visit (Safety Population)
* Usage Notes: Summarizes observed values and changes from baseline
*              for safety-population subjects by parameter, treatment,
*              and visit.
*
* SAS Version: 9.4
* Operating System: SAS OnDemand Linux server (client: Windows 11)
*
* Author: ANSANIA SALAM
* Date Created: 10JUN2026
* Modification History: 07OCT2026
*******************************************************************/

LIBNAME ADAM "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/ADaM";

/* Observed values */

PROC SUMMARY DATA=ADAM.ADVS NWAY;
WHERE SAFFL='Y' AND NOT MISSING(AVAL);
CLASS PARAM TRTPN TRTP AVISITN AVISIT;
VAR AVAL;
OUTPUT OUT=ADVS_AVAL
N=_N
MEAN=_MEAN
MEDIAN=_MED
STD=_SD
MIN=_MIN
MAX=_MAX;
RUN;

DATA ADVS_AVAL2;
SET ADVS_AVAL;
AVAL_N=PUT(_N,4.);
AVAL_MIN=PUT(_MIN,4.);
AVAL_MAX=PUT(_MAX,4.);
AVAL_MEDIAN=PUT(_MED,5.1);
AVAL_MEAN=PUT(_MEAN,5.1);
AVAL_STD=PUT(_SD,6.2);
DROP _:;
RUN;

/* Change from baseline */

PROC SUMMARY DATA=ADAM.ADVS NWAY;
WHERE SAFFL='Y' AND NOT MISSING(CHG);
CLASS PARAM TRTPN TRTP AVISITN AVISIT;
VAR CHG;
OUTPUT OUT=ADVS_CHG
N=_N
MEAN=_MEAN
MEDIAN=_MED
STD=_SD
MIN=_MIN
MAX=_MAX;
RUN;

DATA ADVS_CHG2;
SET ADVS_CHG;
CHG_N=PUT(_N,4.);
CHG_MIN=PUT(_MIN,4.);
CHG_MAX=PUT(_MAX,4.);
CHG_MEDIAN=PUT(_MED,5.1);
CHG_MEAN=PUT(_MEAN,5.1);
CHG_STD=PUT(_SD,6.2);
DROP _:;
RUN;

/* Sort both summary datasets before merging */

PROC SORT DATA=ADVS_AVAL2;
BY PARAM TRTPN TRTP AVISITN AVISIT;
RUN;

PROC SORT DATA=ADVS_CHG2;
BY PARAM TRTPN TRTP AVISITN AVISIT;
RUN;

/* Combine observed and change-from-baseline statistics */

DATA FINAL;
MERGE ADVS_AVAL2 ADVS_CHG2;
BY PARAM TRTPN TRTP AVISITN AVISIT;
RUN;

%INCLUDE "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/Macro/RTF.sas";
OPTIONS ORIENTATION=LANDSCAPE;
TITLE1 J=L "PHARMA Private Limited.";
TITLE2 J=L "Protocol: 043-1-2025";
TITLE3 J=C "Table 14.1.5 Summary of Changes in Vital Signs from Baseline to Final Visit (Safety Population)";

FOOTNOTE1 J=L "Ansania_MCC_Immunotherapy_Phase1/MCCTables/T_14_1_5.sas";
ODS ESCAPECHAR='^';
ODS RTF FILE= "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/OUTPUTS/T_14_1_5.RTF"
STYLE=Styles.Test;

PROC REPORT DATA=FINAL NOWD STYLE={OUTPUTWIDTH=100%} MISSING SPLIT='|';
COLUMN PARAM TRTPN TRTP AVISITN AVISIT
("Observed" "---------------------------------------"
AVAL_N AVAL_MEAN AVAL_MEDIAN AVAL_STD AVAL_MIN AVAL_MAX)
("CFB" "------------------------------------------"
CHG_N CHG_MEAN CHG_MEDIAN CHG_STD CHG_MIN CHG_MAX);

DEFINE PARAM / ORDER NOPRINT;
DEFINE TRTPN / ORDER NOPRINT;

DEFINE TRTP / ORDER "Planned|Treatment"
STYLE(COLUMN)={JUST=L CELLWIDTH=10%}
STYLE(HEADER)={JUST=L CELLWIDTH=10%};

DEFINE AVISITN / ORDER NOPRINT;

DEFINE AVISIT / ORDER "Visit"
STYLE(COLUMN)={JUST=L CELLWIDTH=15%}
STYLE(HEADER)={JUST=L CELLWIDTH=15%};

DEFINE AVAL_N / "n"
STYLE(COLUMN)={JUST=L CELLWIDTH=3%}
STYLE(HEADER)={JUST=L CELLWIDTH=3%};

DEFINE AVAL_MEAN / "Mean"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE AVAL_MEDIAN / "Median"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE AVAL_STD / "SD"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE AVAL_MIN / "Min"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE AVAL_MAX / "Max"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE CHG_N / "n"
STYLE(COLUMN)={JUST=L CELLWIDTH=3%}
STYLE(HEADER)={JUST=L CELLWIDTH=3%};

DEFINE CHG_MEAN / "Mean"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE CHG_MEDIAN / "Median"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE CHG_STD / "SD"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE CHG_MIN / "Min"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

DEFINE CHG_MAX / "Max"
STYLE(COLUMN)={JUST=L CELLWIDTH=5%}
STYLE(HEADER)={JUST=L CELLWIDTH=5%};

COMPUTE BEFORE _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERBOTTOMWIDTH=0.5PT]}";
LINE@1 "Parameter: " PARAM $;
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

BREAK AFTER PARAM / PAGE;
RUN;

ODS _ALL_ CLOSE;
