/*******************************************************************
* Client: PHARMA Private Limited.
* Project: Protocol: 043-1-2025
* Program: T_14_1_6.SAS
*
* Program Type: Table
*
* Purpose: To produce Table 14.1.6 Shift Table from Baseline to End
*          of Period (Safety Population)
* Usage Notes: Summarizes baseline and end-of-period laboratory
*              categories for Chemistry and Hematology.
*
* SAS Version: Base SAS 9.4_M8
* Operating System: SAS OnDemand Linux server (client: Windows 11)
*
* Author: ANSANIA SALAM
* Date Created: 15JUN2026
* Modification History: 07OCT2026
*******************************************************************/

LIBNAME ADAM "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/ADaM";

/* Header cap N - use the total ADSL safety population */

PROC SQL NOPRINT;
SELECT COUNT(DISTINCT USUBJID)
INTO :BIGN1 TRIMMED
FROM ADAM.ADSL
WHERE SAFFL='Y';
QUIT;

%PUT &BIGN1;

/* Keep safety-population Chemistry and Hematology records */
DATA ADLB;
SET ADAM.ADLB;
WHERE SAFFL='Y'
AND UPCASE(STRIP(PARCAT1)) IN ('CHEMISTRY','HEMATOLOGY');

LENGTH BNRINDC $8 ANRINDC $8;

/* Preserve missing baseline/result categories as separate categories */
IF MISSING(BNRIND) THEN BNRINDC='MISSING';
ELSE BNRINDC=UPCASE(STRIP(BNRIND));

IF MISSING(ANRIND) THEN ANRINDC='MISSING';
ELSE ANRINDC=UPCASE(STRIP(ANRIND));

KEEP USUBJID PARCAT1 PARAM AVISITN AVISIT BNRINDC ANRINDC;
RUN;

/* Select each subject's last available visit for each parameter */
PROC SORT DATA=ADLB;
BY USUBJID PARCAT1 PARAM AVISITN AVISIT;
RUN;

DATA ADLB_LAST;
SET ADLB;
BY USUBJID PARCAT1 PARAM AVISITN AVISIT;
IF LAST.PARAM;
RUN;

/* Count unique subjects in each baseline-to-end category combination */
PROC SQL;
CREATE TABLE SHIFT_COUNTS AS
SELECT PARCAT1,
       PARAM,
       BNRINDC,
       COUNT(DISTINCT CASE WHEN ANRINDC='LOW'
                           THEN USUBJID END) AS N_LOW,
       COUNT(DISTINCT CASE WHEN ANRINDC='NORMAL'
                           THEN USUBJID END) AS N_NORMAL,
       COUNT(DISTINCT CASE WHEN ANRINDC='HIGH'
                           THEN USUBJID END) AS N_HIGH,
       COUNT(DISTINCT CASE WHEN ANRINDC='MISSING'
                           THEN USUBJID END) AS N_MISSING
FROM ADLB_LAST
GROUP BY PARCAT1, PARAM, BNRINDC;
QUIT;


/* Set baseline-category order and format counts/percentages */
DATA FINAL;
SET SHIFT_COUNTS;
LENGTH LOW NORMAL HIGH MISSING $30;
LENGTH BASEORD 8;

IF BNRINDC='LOW' THEN BASEORD=1;
ELSE IF BNRINDC='NORMAL' THEN BASEORD=2;
ELSE IF BNRINDC='HIGH' THEN BASEORD=3;
ELSE BASEORD=4;

IF BNRINDC='MISSING' THEN BNRINDC='Missing';

IF N_LOW=0 THEN LOW='0';
ELSE IF &BIGN1>0 THEN
LOW=STRIP(PUT(N_LOW,4.))||' ('||
    STRIP(PUT(N_LOW/&BIGN1*100,5.1))||')';
ELSE LOW=STRIP(PUT(N_LOW,4.));

IF N_NORMAL=0 THEN NORMAL='0';
ELSE IF &BIGN1>0 THEN
NORMAL=STRIP(PUT(N_NORMAL,4.))||' ('||
       STRIP(PUT(N_NORMAL/&BIGN1*100,5.1))||')';
ELSE NORMAL=STRIP(PUT(N_NORMAL,4.));

IF N_HIGH=0 THEN HIGH='0';
ELSE IF &BIGN1>0 THEN
HIGH=STRIP(PUT(N_HIGH,4.))||' ('||
     STRIP(PUT(N_HIGH/&BIGN1*100,5.1))||')';
ELSE HIGH=STRIP(PUT(N_HIGH,4.));

IF N_MISSING=0 THEN MISSING='0';
ELSE IF &BIGN1>0 THEN
MISSING=STRIP(PUT(N_MISSING,4.))||' ('||
        STRIP(PUT(N_MISSING/&BIGN1*100,5.1))||')';
ELSE MISSING=STRIP(PUT(N_MISSING,4.));
RUN;

PROC SORT DATA=FINAL;
BY PARCAT1 PARAM BASEORD;
RUN;

/* Add page numbering */
DATA FINAL;
SET FINAL;
RETAIN LNT PAG1 0;
LNT+1;

IF LNT>15 THEN DO;
PAG1=PAG1+1;
LNT=1;
END;
RUN;

/* Report */
%INCLUDE "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/Macro/RTF.sas";
OPTIONS ORIENTATION=LANDSCAPE;
TITLE1 J=L "PHARMA Private Limited.";
TITLE2 J=L "Protocol: 043-1-2025";
TITLE3 J=C "Table 14.1.6 Shift Table from Baseline to End of Period (Safety Population)";
FOOTNOTE1 J=L "Ansania_MCC_Immunotherapy_Phase1/MCCTables/T_14_1_6.sas";
ODS ESCAPECHAR='^';
ODS RTF FILE= "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/OUTPUTS/T_14_1_6.RTF"
STYLE=Styles.Test;


PROC REPORT DATA=FINAL NOWD STYLE={OUTPUTWIDTH=100%} MISSING SPLIT='|';
COLUMN PAG1 PARCAT1 PARAM BNRINDC BASEORD
       ("Treatment end (N=&BIGN1)" LOW NORMAL HIGH MISSING);

DEFINE PAG1 / ORDER NOPRINT;
DEFINE PARCAT1 / ORDER "Parameter|Category"
STYLE(COLUMN)={JUST=L CELLWIDTH=15%}
STYLE(HEADER)={JUST=L CELLWIDTH=15%};

DEFINE PARAM / ORDER "Parameter (Unit)"
STYLE(COLUMN)={JUST=L CELLWIDTH=25%}
STYLE(HEADER)={JUST=L CELLWIDTH=25%};

DEFINE BNRINDC / DISPLAY "Baseline"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE BASEORD / ORDER NOPRINT;

DEFINE LOW / DISPLAY "LOW"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE NORMAL / DISPLAY "NORMAL"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE HIGH / DISPLAY "HIGH"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE MISSING / DISPLAY "Missing"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

COMPUTE BEFORE _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE BEFORE PARAM;
LINE '';
ENDCOMP;

BREAK AFTER PAG1 / PAGE;
RUN;

ODS _ALL_ CLOSE;
