/*******************************************************************
* Client: PHARMA Private Limited.
* Project: Protocol: 043-1-2025
* Program: T_14_1_3.SAS
*
* Program Type: Table
*
* Purpose: To produce Table 14.1.3 Subject Demographics - Sex and Race
*          (Safety Population)
* Usage Notes: Reports counts and percentages for sex and race by
*              treatment group and overall.
*
* SAS Version: Base SAS 9.4_M8
* Operating System: SAS OnDemand Linux server (client: Windows 11)
*
* Author: ANSANIA SALAM
* Date Created: 30MAY2026
* Modification History: 070CT2026
*******************************************************************/

LIBNAME ADAM "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/ADaM";

/* Header cap N / big N counts - always take from ADSL */

DATA ADSL1;
SET ADAM.ADSL;
IF SAFFL='Y';
OUTPUT;
TRT01AN=5;
TRT01A='ALL';
OUTPUT;
KEEP USUBJID TRT01AN TRT01A;
RUN;

PROC SQL NOPRINT;
CREATE TABLE TRT AS
SELECT TRT01AN, TRT01A, COUNT(DISTINCT USUBJID) AS DENOM
FROM ADSL1
GROUP BY TRT01AN, TRT01A
ORDER BY TRT01AN, TRT01A;

SELECT DENOM INTO :BIGN1-:BIGN5
FROM TRT;
QUIT;

%PUT &BIGN1 &BIGN2 &BIGN3 &BIGN4 &BIGN5;

/* Body part */

DATA ADSL2;
SET ADAM.ADSL;
IF SAFFL='Y';
OUTPUT;
TRT01AN=5;
TRT01A='ALL';
OUTPUT;
KEEP USUBJID TRT01AN TRT01A SEX RACE;
RUN;

/* Gender counts */

DATA CAT_LONG;
SET ADSL2;
LENGTH CAT $20 STAT $100;

IF UPCASE(STRIP(SEX)) IN ('M','MALE') THEN DO;
CATN=1;
CAT='Gender';
OD=1;
STAT='Male';
OUTPUT;
END;

IF UPCASE(STRIP(SEX)) IN ('F','FEMALE') THEN DO;
CATN=1;
CAT='Gender';
OD=2;
STAT='Female';
OUTPUT;
END;

/* Race counts */

IF UPCASE(STRIP(RACE))='ASIAN' THEN DO;
CATN=2;
CAT='Race';
OD=1;
STAT='Asian';
OUTPUT;
END;

IF UPCASE(STRIP(RACE)) IN ('BLACK OR AFRICAN AMERICAN','BLACK') THEN DO;
CATN=2;
CAT='Race';
OD=2;
STAT='Black Or African American';
OUTPUT;
END;

IF UPCASE(STRIP(RACE))='WHITE' THEN DO;
CATN=2;
CAT='Race';
OD=3;
STAT='White';
OUTPUT;
END;

IF UPCASE(STRIP(RACE))='OTHER' THEN DO;
CATN=2;
CAT='Race';
OD=4;
STAT='Other';
OUTPUT;
END;

KEEP USUBJID TRT01AN CATN CAT OD STAT;
RUN;

PROC SQL;
CREATE TABLE COUNTS AS
SELECT CATN, CAT, OD, STAT, TRT01AN, COUNT(DISTINCT USUBJID) AS N
FROM CAT_LONG
GROUP BY CATN, CAT, OD, STAT, TRT01AN;
QUIT;

/* Create all rows for every treatment group, including zero counts */

DATA GRID;
LENGTH CAT $20 STAT $100;
DO TRT01AN=1 TO 5;

CATN=1;
CAT='Gender';
OD=1;
STAT='Male';
OUTPUT;

CATN=1;
CAT='Gender';
OD=2;
STAT='Female';
OUTPUT;

CATN=2;
CAT='Race';
OD=1;
STAT='Asian';
OUTPUT;

CATN=2;
CAT='Race';
OD=2;
STAT='Black Or African American';
OUTPUT;

CATN=2;
CAT='Race';
OD=3;
STAT='White';
OUTPUT;

CATN=2;
CAT='Race';
OD=4;
STAT='Other';
OUTPUT;

END;
RUN;

PROC SQL;
CREATE TABLE PCT AS
SELECT G.CATN,
       G.CAT,
       G.OD,
       G.STAT,
       G.TRT01AN,
       COALESCE(C.N,0) AS N,
       T.DENOM,
       CASE
           WHEN T.DENOM>0 THEN COALESCE(C.N,0)/T.DENOM*100
           ELSE 0
       END AS PCT1
FROM GRID AS G
LEFT JOIN COUNTS AS C
ON G.CATN=C.CATN
AND G.OD=C.OD
AND G.TRT01AN=C.TRT01AN
LEFT JOIN TRT AS T
ON G.TRT01AN=T.TRT01AN
ORDER BY G.CATN, G.OD, G.TRT01AN;
QUIT;

DATA PCT;
SET PCT;
LENGTH PCT_VALUE $30;
PCT_VALUE=STRIP(PUT(N,4.))||' ('||
          STRIP(PUT(PCT1,5.1))||')';
RUN;

/* Transpose treatment groups into report columns TRT1-TRT5 */

PROC SORT DATA=PCT;
BY CATN CAT OD STAT;
RUN;

PROC TRANSPOSE DATA=PCT OUT=FINAL(DROP=_NAME_) PREFIX=TRT;
BY CATN CAT OD STAT;
ID TRT01AN;
VAR PCT_VALUE;
RUN;

/* Report */

%INCLUDE "/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/Macro/RTF.sas";

OPTIONS ORIENTATION=LANDSCAPE;

TITLE1 J=L "PHARMA Private Limited.";
TITLE2 J=L "Protocol: 043-1-2025";
TITLE3 J=C "Table 14.1.3 Subject Demographics - Sex and Race (Safety Population)";

FOOTNOTE1 J=L
"Ansania_MCC_Immunotherapy_Phase1/MCCTables/T_14_1_3.sas";

ODS ESCAPECHAR='^';

ODS RTF FILE=
"/home/u64420862/Ansania_MCC_Immunotherapy_Phase1/OUTPUTS/T_14_1_3.RTF"
STYLE=Styles.Test;

PROC REPORT DATA=FINAL NOWD STYLE={OUTPUTWIDTH=100%} MISSING SPLIT='|';
COLUMN CATN CAT OD STAT TRT1 TRT2 TRT3 TRT4 TRT5;

DEFINE CATN / ORDER NOPRINT;

DEFINE CAT / ORDER "Category"
STYLE(COLUMN)={JUST=L CELLWIDTH=9% ASIS=ON}
STYLE(HEADER)={JUST=L CELLWIDTH=9% ASIS=ON};

DEFINE OD / ORDER NOPRINT;

DEFINE STAT / DISPLAY "Statistic"
STYLE(COLUMN)={JUST=L CELLWIDTH=30% ASIS=ON}
STYLE(HEADER)={JUST=L CELLWIDTH=30% ASIS=ON};

DEFINE TRT1 / DISPLAY "DRUG A|(N=&BIGN1)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE TRT2 / DISPLAY "DRUG B|(N=&BIGN2)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE TRT3 / DISPLAY "DRUG C|(N=&BIGN3)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE TRT4 / DISPLAY "DRUG D|(N=&BIGN4)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

DEFINE TRT5 / DISPLAY "ALL|(N=&BIGN5)"
STYLE(COLUMN)={JUST=L CELLWIDTH=12%}
STYLE(HEADER)={JUST=L CELLWIDTH=12%};

COMPUTE BEFORE _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE@1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE BEFORE CATN;
LINE '';
ENDCOMP;

RUN;

ODS _ALL_ CLOSE;









